# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
project_name: caterpillar
builds:
- env:
  - CGO_ENABLED=0
  ignore:
  - goos: darwin
  - goos: linux
    goarch: 386
archives:
  -
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    replacements:
      linux: Linux
      amd64: x86_64
    wrap_in_directory: false
    files:
    - zzzz*
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
env_files:
  github_token: .github_token
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
release:
  prerelease: auto
  disable: true
nfpms:
  -
    replacements:
      amd64: 64-bit
      386: 32-bit
      linux: Tux
    vendor: "AddictMUD Ltd"
    license: "Free and open source; credit required"
    maintainer: "dburke@addictmud.org"
    description: "The provisioning REST api."
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    formats:
      - rpm
      - deb
    bindir: "/usr/local/bin"

